#! /bin/sh

setxkbmap -layout fr
setxkbmap -option caps:escape &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        0
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off

sleep 0.3
$HOME/.config/polybar/launch.sh
wal -R
picom &
dunst &
dropbox &
